version: "3.7"

services:
  db:
    image: postgres:15.4-alpine3.18
    env_file:
      - envs/.postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/database/postgres:/var/lib/postgresql/data

  backend:
    build: .
    env_file:
      - envs/.postgres.env
      - envs/.django.env
    environment:
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DEBUG=False
      - GUNICORN_CONF=conf.prod.py
    ports:
      - "8080:8080"
    volumes:
      - ./backend/database/postgres:/project/database
      - static:/static
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static:
