version: "3.7"

services:
  backend:
    env_file:
      - envs/.django.env
    environment:
      - DJANGO_DB_ENGINE=django.db.backends.sqlite3
      - DJANGO_DEBUG=True
      - GUNICORN_CONF=conf.py
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend/database:/project/database
      - static:/static
  
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - backend

volumes:
  static:
