version: "3.7"

services:
  backend:
    # env_file:
    #   - .env
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./backend/database:/project/database
      - static:/static
  
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static:
