# Generated by Django 4.2.4 on 2023-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeownercz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='id',
        ),
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.SlugField(help_text='Link to the image of the property', max_length=512),
        ),
        migrations.AlterField(
            model_name='property',
            name='locality',
            field=models.CharField(help_text='Location of the property', max_length=128),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(help_text='Name of the property', max_length=128),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(help_text='Price of the property', max_length=128),
        ),
        migrations.AlterField(
            model_name='property',
            name='url',
            field=models.SlugField(help_text='Link to the property listing', max_length=256, primary_key=True, serialize=False),
        ),
    ]
